site_name: ASC-draft
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.top
    - navigation.path
    - header.autohide
    - foc.follow
  font:
    text: Karla # Open Sans
  language: en
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode
      primary: deep purple
      accent: teal

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: deep purple
      accent: teal
plugins:
  - search
extra:
  generator: false
  analytics:
    provider: google
    property: G-${{ GA_MEASUREMENT_ID }}
#  version:
#    provider: mike
nav:
  - Home: index.md
  - About:
    - About/About.md
  - Modpack:
    - Modpack/Modpack Modrinth.md
    - Modpack/Modpack.md
  - Story:
    - Story/Story.md