site_name: ASC-draft
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.top
    - navigation.path
    - header.autohide
  font:
    text: Karla # Open Sans
  language: en
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb 
        name: Switch to dark mode
      primary: deep purple
      accent: teal

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: deep purple
      accent: teal
plugins:
  - search
extra:
  generator: false